name: your-env-name
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  
  # C++ dependencies
  - cmake
  - make
  - cxx-compiler
  - glew
  - glfw
  - glm
  - freeglut
  - mesalib
  - libglvnd
  - xorg-libxxf86vm
  
  # Pytorch packages
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  
  # Diffusion
  - pip:
      - diffusers
      - transformers
      - accelerate
      - scipy
      - opencv-python
      - matplotlib
